const TransactionTypes = Object.freeze({
    INCOME: "INCOME",
    EXPENSE: "EXPENSE",
    REVERSE:"REVERSE",
    DEPOSIT:"DEPOSIT",
    LOAN:"LOAN",
    DEBIT:"DEBIT",
    CREDIT:"CREDIT"
  });
const GL_TYPES = Object.freeze({
  INVENTORY_GL:"INVENTORY_GL",
  ASSET_GL:"ASSET_GL",
  EXPENSE_GL : "EXPENSE_GL",
  LIABILITY_GL : "LIABILITY_GL",
  INCOME_GL: "INCOME_GL",
});

const ACCOUNT_TYPES = Object.freeze({
  CASH_GL:"CashGL",
  ASSET_GL:"AssetGL",
  BANK_GL : "BankGL",
  PRODUCT_GL : "ProductGL",
  EXPENSE_GL: "ExpenseGL",
  INCOME_GL: "IncomeGL",
  EXTRA_CHARGE_GL: "ExtraChargeGL",
  DRAWING_GL: "DrawingGL",
  LOAN_GL: "LoanGL",
  LIABILITY_GL: "LiabilityGL",
})

const APPCONFIGURATIONS = Object.freeze({
  STARTING_DATE: "STARTING_DATE",
})

const TRANSACTION_CATEGORY = Object.freeze({
  PRODUCT_SALE: "PRODUCT_SALE",
  PRODUCT_SALE_RETURN: "PRODUCT_SALE_RETURN",
  PRODUCT_PURCHASE:"PRODUCT_PURCHASE",
  PRODUCT_PURCHASE_RETURN:"PRODUCT_PURCHASE_RETURN",
  CASH_TRANSACTION:"CASH_TRANSACTION",
  CASH_RETURN:"CASH_RETURN",
  DISCOUNT:"DISCOUNT",
  EXTRA_CHARGE:"EXTRA_CHARGE",
  EXPENSE:"EXPENSE",
})
module.exports = {TransactionTypes, GL_TYPES,APPCONFIGURATIONS,ACCOUNT_TYPES,TRANSACTION_CATEGORY};